# Site settings
title: Recipe Thing
email: nick.howson@gmail.com
description: Recepie things!
# the subpath of your site, e.g. /blog/
baseurl: "" 
# the base hostname & protocol for your site
url: "http://localhost:4001/"
encoding: utf-8
# permalink: none

# Tag pages
tag_page_layout: tag_page
tag_page_dir: tag

#Collection settings
collections:
 recipes:
   output: true
# Build settings
exclude: ["start_devserver.bat", "Gemfile", "Gemfile.lock"]