# Site settings
title: Recipe Thing
email: nick.howson@gmail.com
description: Recepie things!
# the subpath of your site, e.g. /blog/
baseurl: "recipe-thing" 
# the base hostname & protocol for your site
# url: "https://www.googledrive.com/host/0B7-xHCmgECd2TWY2NnFWWXY4ckU"
encoding: utf-8
# permalink: none
#Collection settings
collections:
 recipes:
  output: true
# Build settings
exclude: ["start_devserver.bat", "Gemfile", "Gemfile.lock", "rakefile"]